[package]
name = "aalcalc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
glob = "0.3.0"
profiling = "1.0.7"


[profile.release]
incremental = true
debug = true
lto = "fat"